main: ca.docilecraft.Prefixed
name: Prefixed
author: Doggyroc
website: http://dev.bukkit.org/server-mods/prefixed/
version: 3.0
softdepend: [Vault, TagAPI]
commands:
    Prefixed:
        description: Prefixed command for reloading config and checking prefixes and suffixes.
permissions:
    Prefixed.admin:
        description: Allows player to reload config, check prefixes and suffixes, and toggle debug.
        default: op
    Prefixed.colour:
        description: Allows talking in colour.
        default: op
    Prefixed.colour.black:
        description: Both tab list and name tag turn black.
        default: false
    Prefixed.colour.dblue:
        description: Both tab list and name tag turn dark blue.
        default: false
    Prefixed.colour.dgreen:
        description: Both tab list and name tag turn dark green.
        default: false
    Prefixed.colour.daqua:
        description: Both tab list and name tag turn dark aqua.
        default: false
    Prefixed.colour.dred:
        description: Both tab list and name tag turn dark red.
        default: false
    Prefixed.colour.purple:
        description: Both tab list and name tag turn purple.
        default: false
    Prefixed.colour.gold:
        description: Both tab list and name tag turn gold.
        default: false
    Prefixed.colour.grey:
        description: Both tab list and name tag turn grey.
        default: false
    Prefixed.colour.dgrey:
        description: Both tab list and name tag turn dark grey.
        default: false
    Prefixed.colour.indigo:
        description: Both tab list and name tag turn indigo.
        default: false
    Prefixed.colour.bgreen:
        description: Both tab list and name tag turn bright green.
        default: false
    Prefixed.colour.aqua:
        description: Both tab list and name tag turn aqua.
        default: false
    Prefixed.colour.red:
        description: Both tab list and name tag turn red.
        default: false
    Prefixed.colour.pink:
        description: Both tab list and name tag turn pink.
        default: false
    Prefixed.colour.yellow:
        description: Both tab list and name tag turn yellow.
        default: false
    Prefixed.colour.random:
        description: Both tab list and name tag turn into random letters.
        default: false
    Prefixed.colour.bold:
        description: Both tab list and name tag turn into bolded letters.
        default: false
    Prefixed.colour.strike:
        description: Both tab list and name tag turn into striked letters.
        default: false
    Prefixed.colour.underline:
        description: Both tab list and name tag turn into underlined letters.
        default: false
    Prefixed.colour.italic:
        description: Both tab list and name tag turn into italicised letters.
        default: false