main: ca.docilecraft.Prefixed
name: Prefixed
author: WindX
website: http://dev.bukkit.org/server-mods/prefixed/
version: 4.0
softdepend: [Vault]
commands:
    Prefixed:
        description: Prefixed universal command
permissions:
    Prefixed.admin:
        description: Allows player to reload config, check prefixes and suffixes, and toggle debug.
        default: op
    Prefixed.color:
        description: Allows talking in color.
        default: op
    Prefixed.color.black:
        description: Tab list name turn black.
        default: false
    Prefixed.color.darkblue:
        description: Tab list name turn dark blue.
        default: false
    Prefixed.color.darkgreen:
        description: Tab list name turn dark green.
        default: false
    Prefixed.color.darkaqua:
        description: Tab list name turn dark aqua.
        default: false
    Prefixed.color.darkred:
        description: Tab list name turn dark red.
        default: false
    Prefixed.color.purple:
        description: Tab list name turn purple.
        default: false
    Prefixed.color.gold:
        description: Tab list name turn gold.
        default: false
    Prefixed.color.gray:
        description: Tab list name turn gray.
        default: false
    Prefixed.color.darkgray:
        description: Tab list name turn dark gray.
        default: false
    Prefixed.color.blue:
        description: Tab list name turn blue.
        default: false
    Prefixed.color.green:
        description: Tab list name turn green.
        default: false
    Prefixed.color.aqua:
        description: Tab list name turn aqua.
        default: false
    Prefixed.color.red:
        description: Tab list name turn red.
        default: false
    Prefixed.color.pink:
        description: Tab list name turn pink.
        default: false
    Prefixed.color.yellow:
        description: Tab list name turn yellow.
        default: false
    Prefixed.color.obfuscated:
        description: Tab list name turn into obfuscated letters.
        default: false
    Prefixed.color.bold:
        description: Tab list name turn into bolded letters.
        default: false
    Prefixed.color.strike:
        description: Tab list name turn into striked letters.
        default: false
    Prefixed.color.underline:
        description: Tab list name turn into underlined letters.
        default: false
    Prefixed.color.italic:
        description: Tab list name turn into italicised letters.
        default: false